import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { GeneratedQuestion, generateQuestionFlow } from '@/data/questions';

export interface QAItem {
  questionId: string;
  questionText: string;
  questionLabel: string;
  answer: string;
  phase: string;
}

// Part B: 단어→문장 변환 아이템
export interface SentenceItem {
  id: string;
  keywords: string[]; // 대표단어 1~2개
  sentence: string;   // 변환된 문장
  sourceQAIds: string[]; // 어떤 QA에서 왔는지
}

// 댓글 인터페이스
export interface CommentItem {
  id: string;
  poemId: string;
  authorId: string;
  authorName: string;
  authorAvatar: string;
  text: string;
  createdAt: string;
  likes: number;
  likedBy: string[];
}

export interface PoemDraft {
  id: string;
  flowerId: string;
  authorName: string;
  authorId: string;
  qaItems: QAItem[];
  sentences: SentenceItem[];
  partBText: string;
  partCText: string;
  title: string;
  finalPoem: string;
  background: string;
  isCompleted: boolean;
  isAutoGenerated: boolean;
  createdAt: string;
  likes: number;
  likedBy: string[];
  views: number;
  reports: ReportItem[];
  isHidden: boolean;
  comments: CommentItem[];
}

export interface ReportItem {
  reporterId: string;
  reporterName: string;
  reason: string;
  createdAt: string;
}

export interface Notification {
  id: string;
  type: 'like' | 'view_milestone' | 'achievement' | 'comment';
  message: string;
  poemId?: string;
  createdAt: string;
  isRead: boolean;
}

export interface Achievement {
  id: string;
  title: string;
  description: string;
  emoji: string;
  condition: string;
  unlockedAt?: string;
}

export const ALL_ACHIEVEMENTS: Achievement[] = [
  { id: 'first-poem', title: '첫 발자국', description: '첫 번째 시를 완성했어요', emoji: '🌱', condition: 'poems >= 1' },
  { id: 'three-poems', title: '꾸준한 시인', description: '시를 3편 완성했어요', emoji: '🌿', condition: 'poems >= 3' },
  { id: 'five-poems', title: '열정의 시인', description: '시를 5편 완성했어요', emoji: '🌳', condition: 'poems >= 5' },
  { id: 'ten-poems', title: '시의 숲', description: '시를 10편 완성했어요', emoji: '🏔️', condition: 'poems >= 10' },
  { id: 'first-like', title: '첫 공감', description: '처음으로 좋아요를 받았어요', emoji: '💕', condition: 'likes >= 1' },
  { id: 'ten-likes', title: '공감의 물결', description: '좋아요를 10개 받았어요', emoji: '🌊', condition: 'likes >= 10' },
  { id: 'fifty-likes', title: '마음을 울리다', description: '좋아요를 50개 받았어요', emoji: '🎵', condition: 'likes >= 50' },
  { id: 'all-flowers', title: '꽃 도감 완성', description: '모든 꽃으로 시를 써봤어요', emoji: '🌺', condition: 'flowers >= 6' },
  { id: 'ten-views', title: '작은 독자', description: '내 시를 10명이 읽었어요', emoji: '👀', condition: 'views >= 10' },
  { id: 'fifty-views', title: '떠오르는 시인', description: '내 시를 50명이 읽었어요', emoji: '⭐', condition: 'views >= 50' },
  { id: 'share-first', title: '나눔의 시작', description: '처음으로 시를 공유했어요', emoji: '🤝', condition: 'shares >= 1' },
  { id: 'auto-complete', title: '영감의 도움', description: '자동 완성 기능을 사용했어요', emoji: '✨', condition: 'auto >= 1' },
];

export interface UserProfile {
  id: string;
  name: string;
  email?: string;
  avatar: string;
  collectedFlowers: string[];
  pencils: number; // 연필 (크레딧 대신)
  achievements: string[];
  shareCount: number;
  totalLikes: number;
  totalViews: number;
  isAdmin: boolean;
  isEmailVerified: boolean;
  verificationCode?: string;
  createdAt?: string;
  referralCode?: string; // 내 추천인 코드
  referredBy?: string; // 누구의 추천으로 가입했는지
  usedReferralCodes?: string[]; // 이미 사용한 추천 코드 목록
}

type WritingPhase = 'select-flower' | 'part-a' | 'part-b' | 'part-c' | 'finalize';

// Simple hash function for client-side password hashing
// In production, use bcrypt on the server
function simpleHash(str: string): string {
  let hash = 0;
  const salt = 'sigeuldam-salt-2026';
  const salted = salt + str + salt;
  for (let i = 0; i < salted.length; i++) {
    const char = salted.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash; // Convert to 32bit integer
  }
  // Create a longer hash by running multiple rounds
  let result = '';
  for (let round = 0; round < 4; round++) {
    let h = hash + round * 7919;
    for (let i = 0; i < salted.length; i++) {
      h = ((h << 5) - h) + salted.charCodeAt(i) + round;
      h = h & h;
    }
    result += Math.abs(h).toString(36);
  }
  return result;
}

interface AppState {
  // Auth
  user: UserProfile | null;
  isLoggedIn: boolean;
  allUsers: UserProfile[];
  setUser: (user: UserProfile | null) => void;
  loginAsAdmin: () => void;
  registerUser: (name: string, email: string, password: string) => { user: UserProfile | null; error: string };
  applyReferralCode: (code: string) => { success: boolean; error: string };
  loginUser: (email: string, password: string) => UserProfile | null;
  verifyEmail: (email: string, code: string) => boolean;
  resendVerification: (email: string) => string;
  userPasswords: Record<string, string>; // now stores hashed passwords

  // Writing session
  currentPhase: WritingPhase;
  setPhase: (phase: WritingPhase) => void;
  selectedFlowerId: string | null;
  selectFlower: (flowerId: string) => void;
  authorName: string;
  setAuthorName: (name: string) => void;
  writingLength: 'short' | 'medium' | 'long';
  setWritingLength: (length: 'short' | 'medium' | 'long') => void;

  // Part A
  questionFlow: GeneratedQuestion[];
  currentQuestionIndex: number;
  qaItems: QAItem[];
  initQuestionFlow: () => void;
  answerQuestion: (answer: string) => void;
  nextQuestion: () => void;
  prevQuestion: () => void;
  editAnswer: (questionId: string, newAnswer: string) => void;

  // Part B - sentence building
  sentences: SentenceItem[];
  setSentences: (sentences: SentenceItem[]) => void;
  updateSentence: (id: string, sentence: string) => void;
  addSentence: (sentence: SentenceItem) => void;
  removeSentence: (id: string) => void;
  partBText: string;
  setPartBText: (text: string) => void;
  partBPromptIndex: number;
  nextPartBPrompt: () => void;

  // Part C
  partCText: string;
  setPartCText: (text: string) => void;
  partCOptionIndex: number;
  partCRejections: number;
  setPartCOption: (index: number) => void;
  rejectPartCOption: () => void;
  showFreeMessage: boolean;

  // Final
  poemTitle: string;
  setPoemTitle: (title: string) => void;
  finalPoem: string;
  setFinalPoem: (poem: string) => void;
  poemBackground: string;
  setPoemBackground: (bg: string) => void;

  // Poems collection
  poems: PoemDraft[];
  addPoem: (poem: PoemDraft) => void;
  likePoem: (poemId: string, userId: string) => void;
  unlikePoem: (poemId: string, userId: string) => void;
  viewPoem: (poemId: string) => void;
  reportPoem: (poemId: string, report: ReportItem) => void;
  hidePoem: (poemId: string) => void;
  unhidePoem: (poemId: string) => void;

  // Comments
  addComment: (poemId: string, comment: CommentItem) => void;
  likeComment: (poemId: string, commentId: string, userId: string) => void;
  deleteComment: (poemId: string, commentId: string) => void;

  // Notifications
  notifications: Notification[];
  addNotification: (n: Omit<Notification, 'id' | 'createdAt' | 'isRead'>) => void;
  markNotificationRead: (id: string) => void;
  markAllNotificationsRead: () => void;

  // Achievements
  checkAndUnlockAchievements: () => void;

  // Sharing
  incrementShareCount: () => void;
  showSharePopup: boolean;
  setShowSharePopup: (show: boolean) => void;

  // Pencil (연필) system
  watchAd: () => void;
  usePencil: () => boolean;
  buyPencils: (count: number) => void;

  // Onboarding
  hasCompletedOnboarding: boolean;
  completeOnboarding: () => void;

  // Block users
  blockedUsers: string[];
  blockUser: (userId: string) => void;
  unblockUser: (userId: string) => void;

  // Seed sample poems
  hasSeedData: boolean;
  seedSamplePoems: () => void;

  // Reset
  resetWritingSession: () => void;
}

export const useAppStore = create<AppState>()(
  persist(
    (set, get) => ({
      // Auth
      user: null,
      isLoggedIn: false,
      allUsers: [],
      userPasswords: {},
      setUser: (user) => {
        if (user) {
          const { allUsers } = get();
          const exists = allUsers.find(u => u.id === user.id);
          if (!exists) {
            set({ allUsers: [...allUsers, user] });
          } else {
            set({ allUsers: allUsers.map(u => u.id === user.id ? user : u) });
          }
        }
        set({ user, isLoggedIn: !!user });
      },
      loginAsAdmin: () => {
        const admin: UserProfile = {
          id: 'admin',
          name: '관리자',
          email: 'admin@sigeuldam.kr',
          avatar: '👑',
          collectedFlowers: [],
          pencils: 9999,
          achievements: [],
          shareCount: 0,
          totalLikes: 0,
          totalViews: 0,
          isAdmin: true,
          isEmailVerified: true,
          createdAt: '2026-01-01T00:00:00.000Z',
          referralCode: 'ADMIN',
          usedReferralCodes: [],
        };
        set({ user: admin, isLoggedIn: true });
        const { allUsers } = get();
        if (!allUsers.find(u => u.id === 'admin')) {
          set({ allUsers: [...allUsers, admin] });
        }
      },
      registerUser: (name, email, password) => {
        const { allUsers, userPasswords } = get();

        // Check if email already exists
        if (allUsers.find(u => u.email === email)) {
          return { user: null, error: '이미 사용 중인 이메일입니다.' };
        }

        // Validate email format
        const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
        if (!emailRegex.test(email)) {
          return { user: null, error: '올바른 이메일 형식이 아닙니다.' };
        }

        // Validate password strength
        if (password.length < 8) {
          return { user: null, error: '비밀번호는 8자 이상이어야 합니다.' };
        }
        if (!/[A-Za-z]/.test(password) || !/[0-9]/.test(password)) {
          return { user: null, error: '비밀번호에 영문과 숫자가 모두 포함되어야 합니다.' };
        }

        // Generate verification code
        const verificationCode = Math.floor(100000 + Math.random() * 900000).toString();

        // Generate unique referral code
        const referralCode = name.slice(0, 2).toUpperCase() + Math.random().toString(36).slice(2, 6).toUpperCase();

        // Hash password
        const hashedPassword = simpleHash(password);

        const newUser: UserProfile = {
          id: `user-${Date.now()}`,
          name,
          email,
          avatar: '🌸',
          collectedFlowers: [],
          pencils: 3, // 가입 축하 연필 3개
          achievements: [],
          shareCount: 0,
          totalLikes: 0,
          totalViews: 0,
          isAdmin: false,
          isEmailVerified: false,
          verificationCode,
          createdAt: new Date().toISOString(),
          referralCode,
          usedReferralCodes: [],
        };

        set({
          allUsers: [...allUsers, newUser],
          userPasswords: { ...userPasswords, [email]: hashedPassword },
          user: newUser,
          isLoggedIn: true,
        });

        return { user: newUser, error: '' };
      },
      verifyEmail: (email, code) => {
        const { allUsers, user } = get();
        const targetUser = allUsers.find(u => u.email === email);
        if (!targetUser) return false;
        if (targetUser.verificationCode === code) {
          const updated = { ...targetUser, isEmailVerified: true, verificationCode: undefined };
          set({
            allUsers: allUsers.map(u => u.id === targetUser.id ? updated : u),
            user: user?.id === targetUser.id ? updated : user,
          });
          return true;
        }
        return false;
      },
      resendVerification: (email) => {
        const { allUsers, user } = get();
        const targetUser = allUsers.find(u => u.email === email);
        if (!targetUser) return '';
        const newCode = Math.floor(100000 + Math.random() * 900000).toString();
        const updated = { ...targetUser, verificationCode: newCode };
        set({
          allUsers: allUsers.map(u => u.id === targetUser.id ? updated : u),
          user: user?.id === targetUser.id ? updated : user,
        });
        return newCode;
      },
      loginUser: (email, password) => {
        // Admin check
        if (email === 'admin' && password === 'huruhi24!') {
          get().loginAsAdmin();
          return get().user;
        }
        const { allUsers, userPasswords } = get();
        const hashedInput = simpleHash(password);
        if (userPasswords[email] === hashedInput) {
          const user = allUsers.find(u => u.email === email);
          if (user) {
            set({ user, isLoggedIn: true });
            return user;
          }
        }
        return null;
      },

      // Writing
      currentPhase: 'select-flower',
      setPhase: (phase) => set({ currentPhase: phase }),
      selectedFlowerId: null,
      selectFlower: (flowerId) => set({ selectedFlowerId: flowerId }),
      authorName: '',
      setAuthorName: (name) => set({ authorName: name }),
      writingLength: 'medium',
      setWritingLength: (length) => set({ writingLength: length }),

      // Part A
      questionFlow: [],
      currentQuestionIndex: 0,
      qaItems: [],
      initQuestionFlow: () => {
        const { selectedFlowerId, writingLength } = get();
        if (!selectedFlowerId) return;
        const flow = generateQuestionFlow(selectedFlowerId, writingLength);
        set({ questionFlow: flow, currentQuestionIndex: 0, qaItems: [], sentences: [] });
      },
      answerQuestion: (answer) => {
        const { questionFlow, currentQuestionIndex, qaItems } = get();
        const q = questionFlow[currentQuestionIndex];
        if (!q) return;
        const existing = qaItems.findIndex(item => item.questionId === q.question.id);
        const newItem: QAItem = {
          questionId: q.question.id,
          questionText: q.question.text,
          questionLabel: q.question.label,
          answer,
          phase: q.phase,
        };
        if (existing >= 0) {
          const updated = [...qaItems];
          updated[existing] = newItem;
          set({ qaItems: updated });
        } else {
          set({ qaItems: [...qaItems, newItem] });
        }
      },
      nextQuestion: () => {
        const { currentQuestionIndex, questionFlow } = get();
        if (currentQuestionIndex < questionFlow.length - 1) {
          set({ currentQuestionIndex: currentQuestionIndex + 1 });
        }
      },
      prevQuestion: () => {
        const { currentQuestionIndex } = get();
        if (currentQuestionIndex > 0) {
          set({ currentQuestionIndex: currentQuestionIndex - 1 });
        }
      },
      editAnswer: (questionId, newAnswer) => {
        const { qaItems } = get();
        set({
          qaItems: qaItems.map(item =>
            item.questionId === questionId ? { ...item, answer: newAnswer } : item
          ),
        });
      },

      // Part B - sentence building
      sentences: [],
      setSentences: (sentences) => set({ sentences }),
      updateSentence: (id, sentence) => {
        const { sentences } = get();
        set({ sentences: sentences.map(s => s.id === id ? { ...s, sentence } : s) });
      },
      addSentence: (sentence) => {
        set({ sentences: [...get().sentences, sentence] });
      },
      removeSentence: (id) => {
        set({ sentences: get().sentences.filter(s => s.id !== id) });
      },
      partBText: '',
      setPartBText: (text) => set({ partBText: text }),
      partBPromptIndex: 0,
      nextPartBPrompt: () => {
        const { partBPromptIndex } = get();
        set({ partBPromptIndex: partBPromptIndex + 1 });
      },

      // Part C
      partCText: '',
      setPartCText: (text) => set({ partCText: text }),
      partCOptionIndex: -1,
      partCRejections: 0,
      showFreeMessage: false,
      setPartCOption: (index) => set({ partCOptionIndex: index }),
      rejectPartCOption: () => {
        const { partCRejections } = get();
        const newCount = partCRejections + 1;
        set({ partCRejections: newCount, showFreeMessage: newCount >= 3 });
      },

      // Final
      poemTitle: '',
      setPoemTitle: (title) => set({ poemTitle: title }),
      finalPoem: '',
      setFinalPoem: (poem) => set({ finalPoem: poem }),
      poemBackground: 'bg-cream-100',
      setPoemBackground: (bg) => set({ poemBackground: bg }),

      // Poems
      poems: [],
      addPoem: (poem) => {
        // Ensure comments array exists
        const poemWithComments = { ...poem, comments: poem.comments || [] };
        set(state => ({ poems: [poemWithComments, ...state.poems] }));
        // Update user collected flowers
        const { user } = get();
        if (user && poem.flowerId && !user.collectedFlowers.includes(poem.flowerId)) {
          const updated = { ...user, collectedFlowers: [...user.collectedFlowers, poem.flowerId] };
          get().setUser(updated);
        }
        get().checkAndUnlockAchievements();
      },
      likePoem: (poemId, userId) => {
        set(state => ({
          poems: state.poems.map(p => {
            if (p.id === poemId && !p.likedBy.includes(userId)) {
              return { ...p, likes: p.likes + 1, likedBy: [...p.likedBy, userId] };
            }
            return p;
          }),
        }));
        // Notify poem author
        const poem = get().poems.find(p => p.id === poemId);
        if (poem && poem.authorId !== userId) {
          get().addNotification({
            type: 'like',
            message: `"${poem.title || '무제'}"에 좋아요가 눌렸어요!`,
            poemId,
          });
        }
        get().checkAndUnlockAchievements();
      },
      unlikePoem: (poemId, userId) => {
        set(state => ({
          poems: state.poems.map(p => {
            if (p.id === poemId && p.likedBy.includes(userId)) {
              return { ...p, likes: Math.max(0, p.likes - 1), likedBy: p.likedBy.filter(id => id !== userId) };
            }
            return p;
          }),
        }));
      },
      viewPoem: (poemId) => {
        set(state => ({
          poems: state.poems.map(p =>
            p.id === poemId ? { ...p, views: (p.views || 0) + 1 } : p
          ),
        }));
        const poem = get().poems.find(p => p.id === poemId);
        if (poem) {
          const views = poem.views || 0;
          if (views === 10 || views === 50 || views === 100) {
            get().addNotification({
              type: 'view_milestone',
              message: `"${poem.title || '무제'}"을 ${views}명이 읽었어요!`,
              poemId,
            });
          }
        }
        get().checkAndUnlockAchievements();
      },
      reportPoem: (poemId, report) => {
        set(state => ({
          poems: state.poems.map(p =>
            p.id === poemId ? { ...p, reports: [...(p.reports || []), report] } : p
          ),
        }));
      },
      hidePoem: (poemId) => set(state => ({
        poems: state.poems.map(p => p.id === poemId ? { ...p, isHidden: true } : p),
      })),
      unhidePoem: (poemId) => set(state => ({
        poems: state.poems.map(p => p.id === poemId ? { ...p, isHidden: false } : p),
      })),

      // Comments
      addComment: (poemId, comment) => {
        set(state => ({
          poems: state.poems.map(p =>
            p.id === poemId ? { ...p, comments: [...(p.comments || []), comment] } : p
          ),
        }));
        // Notify poem author
        const poem = get().poems.find(p => p.id === poemId);
        const { user } = get();
        if (poem && user && poem.authorId !== user.id) {
          get().addNotification({
            type: 'comment',
            message: `"${poem.title || '무제'}"에 ${comment.authorName}님이 댓글을 달았어요: "${comment.text.slice(0, 30)}${comment.text.length > 30 ? '...' : ''}"`,
            poemId,
          });
        }
      },
      likeComment: (poemId, commentId, userId) => {
        set(state => ({
          poems: state.poems.map(p => {
            if (p.id !== poemId) return p;
            return {
              ...p,
              comments: (p.comments || []).map(c => {
                if (c.id !== commentId) return c;
                if (c.likedBy.includes(userId)) {
                  return { ...c, likes: Math.max(0, c.likes - 1), likedBy: c.likedBy.filter(id => id !== userId) };
                }
                return { ...c, likes: c.likes + 1, likedBy: [...c.likedBy, userId] };
              }),
            };
          }),
        }));
      },
      deleteComment: (poemId, commentId) => {
        set(state => ({
          poems: state.poems.map(p => {
            if (p.id !== poemId) return p;
            return { ...p, comments: (p.comments || []).filter(c => c.id !== commentId) };
          }),
        }));
      },

      // Notifications
      notifications: [],
      addNotification: (n) => {
        const notification: Notification = {
          ...n,
          id: `notif-${Date.now()}-${Math.random().toString(36).slice(2)}`,
          createdAt: new Date().toISOString(),
          isRead: false,
        };
        set(state => ({ notifications: [notification, ...state.notifications].slice(0, 100) }));
      },
      markNotificationRead: (id) => set(state => ({
        notifications: state.notifications.map(n => n.id === id ? { ...n, isRead: true } : n),
      })),
      markAllNotificationsRead: () => set(state => ({
        notifications: state.notifications.map(n => ({ ...n, isRead: true })),
      })),

      // Achievements
      checkAndUnlockAchievements: () => {
        const { user, poems } = get();
        if (!user) return;
        const myPoems = poems.filter(p => p.authorId === user.id);
        const totalLikes = myPoems.reduce((sum, p) => sum + p.likes, 0);
        const totalViews = myPoems.reduce((sum, p) => sum + (p.views || 0), 0);
        const uniqueFlowers = Array.from(new Set(myPoems.map(p => p.flowerId))).length;
        const hasAuto = myPoems.some(p => p.isAutoGenerated);
        const newAchievements: string[] = [];

        ALL_ACHIEVEMENTS.forEach(a => {
          if (user.achievements.includes(a.id)) return;
          let unlocked = false;
          if (a.condition.startsWith('poems >= ')) unlocked = myPoems.length >= parseInt(a.condition.split('>= ')[1]);
          if (a.condition.startsWith('likes >= ')) unlocked = totalLikes >= parseInt(a.condition.split('>= ')[1]);
          if (a.condition.startsWith('views >= ')) unlocked = totalViews >= parseInt(a.condition.split('>= ')[1]);
          if (a.condition.startsWith('flowers >= ')) unlocked = uniqueFlowers >= parseInt(a.condition.split('>= ')[1]);
          if (a.condition.startsWith('shares >= ')) unlocked = (user.shareCount || 0) >= parseInt(a.condition.split('>= ')[1]);
          if (a.condition === 'auto >= 1') unlocked = hasAuto;
          if (unlocked) newAchievements.push(a.id);
        });

        if (newAchievements.length > 0) {
          const updated = { ...user, achievements: [...user.achievements, ...newAchievements], totalLikes, totalViews };
          get().setUser(updated);
          newAchievements.forEach(aid => {
            const ach = ALL_ACHIEVEMENTS.find(a => a.id === aid);
            if (ach) {
              get().addNotification({
                type: 'achievement',
                message: `업적 달성! ${ach.emoji} ${ach.title}: ${ach.description}`,
              });
            }
          });
        } else {
          // Still update stats
          const updated = { ...user, totalLikes, totalViews };
          if (updated.totalLikes !== user.totalLikes || updated.totalViews !== user.totalViews) {
            set({ user: updated });
          }
        }
      },

      // Sharing
      incrementShareCount: () => {
        const { user } = get();
        if (user) {
          const updated = { ...user, shareCount: (user.shareCount || 0) + 1 };
          get().setUser(updated);
          get().checkAndUnlockAchievements();
        }
      },
      showSharePopup: false,
      setShowSharePopup: (show) => set({ showSharePopup: show }),

      // Referral code
      applyReferralCode: (code) => {
        const { user, allUsers } = get();
        if (!user) return { success: false, error: '로그인이 필요합니다.' };
        // Can't use own code
        if (user.referralCode === code) return { success: false, error: '자신의 추천 코드는 사용할 수 없어요.' };
        // Already used this code
        if ((user.usedReferralCodes || []).includes(code)) return { success: false, error: '이미 사용한 추천 코드입니다.' };
        // Find the referrer
        const referrer = allUsers.find(u => u.referralCode === code);
        if (!referrer) return { success: false, error: '존재하지 않는 추천 코드입니다.' };
        // Give pencil to both
        const updatedUser = {
          ...user,
          pencils: (user.pencils || 0) + 1,
          usedReferralCodes: [...(user.usedReferralCodes || []), code],
        };
        const updatedReferrer = {
          ...referrer,
          pencils: (referrer.pencils || 0) + 1,
        };
        set({
          user: updatedUser,
          allUsers: get().allUsers.map(u => {
            if (u.id === updatedUser.id) return updatedUser;
            if (u.id === updatedReferrer.id) return updatedReferrer;
            return u;
          }),
        });
        // Notify the referrer
        get().addNotification({
          type: 'achievement',
          message: `${user.name}님이 추천 코드를 입력했어요! ✏️ 연필 1자루를 받았습니다.`,
        });
        return { success: true, error: '' };
      },

      // Pencil (연필) system
      watchAd: () => {
        const { user } = get();
        if (user) {
          const updated = { ...user, pencils: (user.pencils || 0) + 1 };
          get().setUser(updated);
        }
      },
      usePencil: () => {
        const { user } = get();
        if (!user) return false;
        if (user.isAdmin) return true; // admin unlimited
        if ((user.pencils || 0) <= 0) return false;
        const updated = { ...user, pencils: (user.pencils || 0) - 1 };
        get().setUser(updated);
        return true;
      },
      buyPencils: (count) => {
        const { user } = get();
        if (user) {
          const updated = { ...user, pencils: (user.pencils || 0) + count };
          get().setUser(updated);
        }
      },

      // Onboarding
      hasCompletedOnboarding: false,
      completeOnboarding: () => set({ hasCompletedOnboarding: true }),

      // Block users
      blockedUsers: [],
      blockUser: (userId) => set(state => ({
        blockedUsers: state.blockedUsers.includes(userId) ? state.blockedUsers : [...state.blockedUsers, userId],
      })),
      unblockUser: (userId) => set(state => ({
        blockedUsers: state.blockedUsers.filter(id => id !== userId),
      })),

      // Seed sample poems
      hasSeedData: false,
      seedSamplePoems: () => {
        const { poems, hasSeedData } = get();
        if (hasSeedData) return;
        const samplePoems: PoemDraft[] = [
          { id: 's1', flowerId: 'lilac', authorName: '별빛', authorId: 'sample-1', qaItems: [], sentences: [], partBText: '', partCText: '', title: '봄바람에게', finalPoem: '라일락 향기 흩날리는\n골목길을 걸으면\n네가 떠오른다\n\n바람이 속삭이듯\n스쳐지나간 그 봄날\n아직도 여기 머문다', background: 'bg-purple-50', isCompleted: true, isAutoGenerated: false, createdAt: '2026-02-20T10:00:00Z', likes: 24, likedBy: [], views: 45, reports: [], isHidden: false, comments: [] },
          { id: 's2', flowerId: 'balloon-flower', authorName: '구름', authorId: 'sample-2', qaItems: [], sentences: [], partBText: '', partCText: '', title: '어린 날의 노래', finalPoem: '풀밭에 누워\n구름을 세던 날\n세상은 참 넓었고\n\n하루는 참 길었다\n그때의 웃음이\n아직 귓가에 맴돈다', background: 'bg-pink-50', isCompleted: true, isAutoGenerated: false, createdAt: '2026-02-19T10:00:00Z', likes: 18, likedBy: [], views: 32, reports: [], isHidden: false, comments: [] },
          { id: 's3', flowerId: 'rose', authorName: '달빛', authorId: 'sample-3', qaItems: [], sentences: [], partBText: '', partCText: '', title: '사랑이란', finalPoem: '가시 위에 핀\n붉은 꽃잎 하나\n\n아프지만 놓을 수 없는\n그 이름을\n오늘도 부른다', background: 'bg-red-50', isCompleted: true, isAutoGenerated: false, createdAt: '2026-02-18T10:00:00Z', likes: 31, likedBy: [], views: 67, reports: [], isHidden: false, comments: [] },
          { id: 's4', flowerId: 'forsythia', authorName: '햇살', authorId: 'sample-4', qaItems: [], sentences: [], partBText: '', partCText: '', title: '희망의 노래', finalPoem: '겨울이 깊을수록\n봄은 가까이 오고\n\n어둠이 짙을수록\n별은 더 밝게 빛나니\n\n우리도 그렇게\n피어나리라', background: 'bg-yellow-50', isCompleted: true, isAutoGenerated: false, createdAt: '2026-02-17T10:00:00Z', likes: 42, likedBy: [], views: 88, reports: [], isHidden: false, comments: [] },
          { id: 's5', flowerId: 'portulaca', authorName: '솜사탕', authorId: 'sample-5', qaItems: [], sentences: [], partBText: '', partCText: '', title: '천진난만', finalPoem: '웃음이 꽃처럼\n피어나는 아이처럼\n\n거짓 없이\n있는 그대로\n아름다운 것들이\n\n세상에 가득하길', background: 'bg-cream-100', isCompleted: true, isAutoGenerated: false, createdAt: '2026-02-16T10:00:00Z', likes: 15, likedBy: [], views: 21, reports: [], isHidden: false, comments: [] },
          { id: 's6', flowerId: 'moss-phlox', authorName: '나무', authorId: 'sample-6', qaItems: [], sentences: [], partBText: '', partCText: '', title: '묵묵한 사랑', finalPoem: '말없이 내려놓은\n따뜻한 밥상 위에\n\n세상 모든 말보다\n깊은 사랑이 있다\n\n그걸 알아차린 건\n한참이 지나서였다', background: 'bg-green-50', isCompleted: true, isAutoGenerated: false, createdAt: '2026-02-15T10:00:00Z', likes: 27, likedBy: [], views: 53, reports: [], isHidden: false, comments: [] },
        ];
        // Only add samples that don't already exist
        const existingIds = new Set(poems.map(p => p.id));
        const newSamples = samplePoems.filter(s => !existingIds.has(s.id));
        if (newSamples.length > 0) {
          set(state => ({ poems: [...state.poems, ...newSamples], hasSeedData: true }));
        } else {
          set({ hasSeedData: true });
        }
      },

      // Reset
      resetWritingSession: () => set({
        currentPhase: 'select-flower',
        selectedFlowerId: null,
        questionFlow: [],
        currentQuestionIndex: 0,
        qaItems: [],
        sentences: [],
        partBText: '',
        partBPromptIndex: 0,
        partCText: '',
        partCOptionIndex: -1,
        partCRejections: 0,
        showFreeMessage: false,
        poemTitle: '',
        finalPoem: '',
        poemBackground: 'bg-cream-100',
        showSharePopup: false,
      }),
    }),
    {
      name: 'sigeuldam-storage',
      partialize: (state) => ({
        user: state.user,
        isLoggedIn: state.isLoggedIn,
        allUsers: state.allUsers,
        userPasswords: state.userPasswords,
        poems: state.poems,
        authorName: state.authorName,
        notifications: state.notifications,
        hasCompletedOnboarding: state.hasCompletedOnboarding,
        blockedUsers: state.blockedUsers,
        hasSeedData: state.hasSeedData,
      }),
    }
  )
);
