import { NextRequest, NextResponse } from 'next/server';
import { createServerSupabase } from '@/lib/supabase';

// GET /api/poems/[id] — get single poem
export async function GET(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const supabase = createServerSupabase();
    if (!supabase) return NextResponse.json({ error: 'DB 연결 실패' }, { status: 503 });

    const { id } = params;
    const { data: p, error } = await supabase.from('poems').select('*').eq('id', id).single();
    if (error || !p) {
      return NextResponse.json({ error: '시를 찾을 수 없습니다.' }, { status: 404 });
    }

    // Get comments
    const { data: commentsData } = await supabase
      .from('comments')
      .select('*')
      .eq('poem_id', id)
      .order('created_at', { ascending: true });

    // Get reports
    const { data: reportsData } = await supabase
      .from('reports')
      .select('*')
      .eq('poem_id', id);

    return NextResponse.json({
      poem: {
        id: p.id,
        flowerId: p.flower_id,
        authorName: p.author_name,
        authorId: p.author_id,
        qaItems: p.qa_items || [],
        sentences: p.sentences || [],
        partBText: p.part_b_text || '',
        partCText: p.part_c_text || '',
        title: p.title || '',
        finalPoem: p.final_poem || '',
        background: p.background || 'bg-cream-100',
        isCompleted: p.is_completed ?? true,
        isAutoGenerated: p.is_auto_generated ?? false,
        isHidden: p.is_hidden ?? false,
        createdAt: p.created_at,
        likes: p.likes || 0,
        likedBy: p.liked_by || [],
        views: p.views || 0,
        reports: (reportsData || []).map(r => ({
          reporterId: r.reporter_id,
          reporterName: r.reporter_name,
          reason: r.reason,
          createdAt: r.created_at,
        })),
        comments: (commentsData || []).map(c => ({
          id: c.id,
          poemId: c.poem_id,
          authorId: c.author_id,
          authorName: c.author_name,
          authorAvatar: c.author_avatar || '🌸',
          text: c.text,
          createdAt: c.created_at,
          likes: c.likes || 0,
          likedBy: c.liked_by || [],
        })),
      }
    });
  } catch (error) {
    console.error('Poem GET error:', error);
    return NextResponse.json({ error: '서버 오류' }, { status: 500 });
  }
}

// DELETE /api/poems/[id]
export async function DELETE(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const supabase = createServerSupabase();
    if (!supabase) return NextResponse.json({ error: 'DB 연결 실패' }, { status: 503 });

    const { id } = params;
    const body = await req.json().catch(() => ({}));
    const { userId } = body;

    // Verify ownership or admin
    const { data: poem } = await supabase.from('poems').select('author_id').eq('id', id).single();
    if (!poem) return NextResponse.json({ error: '시를 찾을 수 없습니다.' }, { status: 404 });

    if (userId && poem.author_id !== userId) {
      // Check if admin
      const { data: user } = await supabase.from('users').select('is_admin').eq('id', userId).single();
      if (!user?.is_admin) {
        return NextResponse.json({ error: '삭제 권한이 없습니다.' }, { status: 403 });
      }
    }

    // Delete comments first
    await supabase.from('comments').delete().eq('poem_id', id);
    await supabase.from('reports').delete().eq('poem_id', id);
    const { error } = await supabase.from('poems').delete().eq('id', id);
    
    if (error) {
      console.error('Delete poem error:', error);
      return NextResponse.json({ error: '삭제에 실패했습니다.' }, { status: 500 });
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    console.error('Poem DELETE error:', error);
    return NextResponse.json({ error: '서버 오류' }, { status: 500 });
  }
}

// PATCH /api/poems/[id] — hide/unhide
export async function PATCH(req: NextRequest, { params }: { params: { id: string } }) {
  try {
    const supabase = createServerSupabase();
    if (!supabase) return NextResponse.json({ error: 'DB 연결 실패' }, { status: 503 });

    const { id } = params;
    const body = await req.json();
    const { isHidden } = body;

    const { error } = await supabase
      .from('poems')
      .update({ is_hidden: isHidden })
      .eq('id', id);

    if (error) {
      return NextResponse.json({ error: '업데이트 실패' }, { status: 500 });
    }

    return NextResponse.json({ success: true });
  } catch (error) {
    return NextResponse.json({ error: '서버 오류' }, { status: 500 });
  }
}
