import { NextRequest, NextResponse } from 'next/server';
import { createServerSupabase } from '@/lib/supabase';

// GET /api/poems — list poems
export async function GET(req: NextRequest) {
  try {
    const supabase = createServerSupabase();
    if (!supabase) return NextResponse.json({ error: 'DB 연결 실패' }, { status: 503 });

    const { searchParams } = new URL(req.url);
    const authorId = searchParams.get('authorId');
    const limit = parseInt(searchParams.get('limit') || '50');
    const offset = parseInt(searchParams.get('offset') || '0');

    let query = supabase
      .from('poems')
      .select('*')
      .eq('is_hidden', false)
      .order('created_at', { ascending: false })
      .range(offset, offset + limit - 1);

    if (authorId) {
      query = query.eq('author_id', authorId);
    }

    const { data: poems, error } = await query;
    if (error) {
      console.error('Fetch poems error:', error);
      return NextResponse.json({ error: '시 목록을 불러오지 못했습니다.' }, { status: 500 });
    }

    // Also get comments for these poems
    const poemIds = (poems || []).map(p => p.id);
    let comments: any[] = [];
    if (poemIds.length > 0) {
      const { data: commentsData } = await supabase
        .from('comments')
        .select('*')
        .in('poem_id', poemIds)
        .order('created_at', { ascending: true });
      comments = commentsData || [];
    }

    // Map to frontend format
    const mapped = (poems || []).map(p => ({
      id: p.id,
      flowerId: p.flower_id,
      authorName: p.author_name,
      authorId: p.author_id,
      qaItems: p.qa_items || [],
      sentences: p.sentences || [],
      partBText: p.part_b_text || '',
      partCText: p.part_c_text || '',
      title: p.title || '',
      finalPoem: p.final_poem || '',
      background: p.background || 'bg-cream-100',
      isCompleted: p.is_completed ?? true,
      isAutoGenerated: p.is_auto_generated ?? false,
      isHidden: p.is_hidden ?? false,
      createdAt: p.created_at,
      likes: p.likes || 0,
      likedBy: p.liked_by || [],
      views: p.views || 0,
      reports: [],
      comments: comments
        .filter(c => c.poem_id === p.id)
        .map(c => ({
          id: c.id,
          poemId: c.poem_id,
          authorId: c.author_id,
          authorName: c.author_name,
          authorAvatar: c.author_avatar || '🌸',
          text: c.text,
          createdAt: c.created_at,
          likes: c.likes || 0,
          likedBy: c.liked_by || [],
        })),
    }));

    return NextResponse.json({ poems: mapped });
  } catch (error) {
    console.error('Poems GET error:', error);
    return NextResponse.json({ error: '서버 오류' }, { status: 500 });
  }
}

// POST /api/poems — create a poem
export async function POST(req: NextRequest) {
  try {
    const supabase = createServerSupabase();
    if (!supabase) return NextResponse.json({ error: 'DB 연결 실패' }, { status: 503 });

    const body = await req.json();
    const { flowerId, authorName, authorId, qaItems, sentences, partBText, partCText, title, finalPoem, background, isCompleted, isAutoGenerated } = body;

    if (!authorId || !finalPoem) {
      return NextResponse.json({ error: '필수 정보가 누락되었습니다.' }, { status: 400 });
    }

    const { data: poem, error } = await supabase.from('poems').insert({
      flower_id: flowerId,
      author_name: authorName,
      author_id: authorId,
      qa_items: qaItems || [],
      sentences: sentences || [],
      part_b_text: partBText || '',
      part_c_text: partCText || '',
      title: title || '',
      final_poem: finalPoem,
      background: background || 'bg-cream-100',
      is_completed: isCompleted ?? true,
      is_auto_generated: isAutoGenerated ?? false,
      is_hidden: false,
      likes: 0,
      liked_by: [],
      views: 0,
    }).select().single();

    if (error || !poem) {
      console.error('Create poem error:', error);
      return NextResponse.json({ error: '시 저장에 실패했습니다.' }, { status: 500 });
    }

    // Update user collected_flowers
    if (flowerId && authorId) {
      const { data: user } = await supabase
        .from('users')
        .select('collected_flowers')
        .eq('id', authorId)
        .single();

      if (user) {
        const flowers = user.collected_flowers || [];
        if (!flowers.includes(flowerId)) {
          await supabase
            .from('users')
            .update({ collected_flowers: [...flowers, flowerId] })
            .eq('id', authorId);
        }
      }
    }

    return NextResponse.json({
      poem: {
        id: poem.id,
        flowerId: poem.flower_id,
        authorName: poem.author_name,
        authorId: poem.author_id,
        qaItems: poem.qa_items || [],
        sentences: poem.sentences || [],
        partBText: poem.part_b_text || '',
        partCText: poem.part_c_text || '',
        title: poem.title || '',
        finalPoem: poem.final_poem || '',
        background: poem.background || 'bg-cream-100',
        isCompleted: poem.is_completed,
        isAutoGenerated: poem.is_auto_generated,
        isHidden: false,
        createdAt: poem.created_at,
        likes: 0,
        likedBy: [],
        views: 0,
        reports: [],
        comments: [],
      }
    });
  } catch (error) {
    console.error('Poems POST error:', error);
    return NextResponse.json({ error: '서버 오류' }, { status: 500 });
  }
}
